// <auto-generated />
using IronWaterStudio_Test_Stoianova.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IronWaterStudio_Test_Stoianova.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128142115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IronWaterStudio_Test_Stoianova.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Из ближайшей пекарни",
                            Name = "Хлеб",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Светаево",
                            Name = "Молоко",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "1 кг",
                            Name = "Курица",
                            Price = 359.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
